---
title: "ExploratoryDataAnalysis"
output: html_document
---

Grupo Bimbo Project

```{r echo=FALSE}
setwd("C:/Users/eladiomontero/GrupoBimbo")
library(data.table)

```

1) Read the data

```{r}
train <- fread('DATA\\train.csv', 
  select = c("Semana","Agencia_ID","Canal_ID",
		"Ruta_SAK","Cliente_ID","Producto_ID",
		"Venta_uni_hoy","Venta_hoy","Dev_uni_proxima",
		"Dev_proxima","Demanda_uni_equil"),
  colClasses=c(Semana="numeric", Agencia_ID="numeric",
		Canal_ID  ="numeric", Ruta_SAK="numeric", 
		Cliente_ID="numeric", Producto_ID="numeric", 
		Venta_uni_hoy="numeric", Venta_hoy="numeric", 
		Dev_uni_proxima="numeric", Dev_proxima="numeric", 
		Demanda_uni_equil="numeric"), nrows = 1000000)

products <- fread('DATA\\cluster_prods(20).csv', 
                  select = c('Producto_ID',  'Cluster'), 
                  colClasses = c(Producto_ID="numeric", Cluster="character"))

clients = fread('DATA\\cliente_tabla.csv')
```

2) Look at the bottom and the top of your data

```{r echo = FALSE}
head(train)
tail(train)

head(products)
tail(products)

head(clients)
tail(clients)

```

3) Check your n's

```{r echo = FALSE}
summary(train)
summary(clients)
summary(products)

```

4) Plots

```{r echo = FALSE}
#library(car)
#scatterplot.matrix(~Semana+Agencia_ID+Canal_ID+Ruta_SAK+Cliente_ID+Producto_ID
#                   |Demanda_uni_equil, data = train, 
#                   main = "Variable Relationship")
```



